services:
  - type: web
    name: lujan-barber-shop
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/barberia-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: barberia-db
          property: connectionString
      - key: PGHOST
        fromDatabase:
          name: barberia-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: barberia-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: barberia-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: barberia-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: barberia-db
          property: password
      - key: PORT
        value: 10000

databases:
  - name: barberia-db
    databaseName: barberia
    user: barberia_user