spring.application.name=barberia

# Base de datos Neon.tech (URL directa)
spring.datasource.url=jdbc:postgresql://ep-dawn-hill-ax0vj81a-pooler.c-4.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oDX6P8hfcEYM
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Puerto
server.port=${PORT:8081}

# Nombre de la barber\u00eda
app.nombre=Barber Shop